name: release stable image

on:
  release:
    types: [published, edited]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: stable

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull, tag and push image to DockerHub
        run: |
          docker pull mehmetahsen/cuberite:${{ github.sha }}
          docker tag  mehmetahsen/cuberite:${{ github.sha }} mehmetahsen/cuberite:stable
          docker push mehmetahsen/cuberite:stable

